services:
  - name: bse-dashboard
    type: web
    env: docker
    repo: https://github.com/paul-antony/bse_dashboard
    repoBranch: scrappy_deployment  # Change to the branch you want to deploy
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: SPLASH_URL
        value: https://splash-server.onrender.com

  - name: splash-server
    type: web
    env: docker
    repo: https://github.com/scrapinghub/splash
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8050